# Generated by Django 4.0.6 on 2022-09-05 02:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sams.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sams.vendor'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 5, 2, 12, 22, 936072, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 5, 2, 12, 22, 954351, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 5, 2, 12, 22, 954166, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
