# Generated by Django 5.0.8 on 2024-09-10 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0004_delete_product_delete_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 10, 2, 16, 48, 455971, tzinfo=datetime.timezone.utc), null=True)),
            ],
        ),
    ]
