# Generated by Django 5.0.8 on 2024-09-10 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0005_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='name',
            new_name='vendor_name',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='type',
            new_name='vendor_type',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 10, 3, 29, 36, 34537, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
