# Generated by Django 5.0.8 on 2024-09-10 03:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc

class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0006_rename_name_vendor_vendor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 10, 3, 29, 50, 388760, tzinfo=utc), null=True),
        ),
    ]
