# Generated by Django 4.0.6 on 2022-09-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0007_alter_vendor_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
