# Generated by Django 4.0.6 on 2024-10-07 04:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0009_alter_vendor_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 7, 4, 12, 31, 410327, tzinfo=utc), null=True),
        ),
    ]
