# Generated by Django 4.0.6 on 2022-09-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0012_alter_product_product_name_alter_product_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sku',
            field=models.CharField(max_length=255),
        ),
    ]
