# Generated by Django 4.0.6 on 2024-10-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0012_vendor_deleted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
