# Generated by Django 4.0.6 on 2022-09-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0013_alter_product_product_name_alter_product_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
