# Generated by Django 4.0.6 on 2024-11-04 01:44

from django.db import migrations, models
from django.utils.timezone import utc
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0014_vendor_sentiment_comments_vendor_sentiment_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 7, 4, 12, 31, 410327, tzinfo=utc), null=True),
        ),
    ]
