# Generated by Django 4.0.6 on 2024-11-04 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0015_alter_vendor_created_date'),
        ('sams', '0016_alter_vendor_created_date'),
    ]

    operations = [
    ]
