# Generated by Django 4.0.6 on 2022-09-05 02:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0002_product_category_product_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 2, 12, 45, 16848, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 2, 12, 45, 29040, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 2, 12, 45, 28870, tzinfo=utc)),
        ),
    ]
